### ISSUE TITLE
Failed to hot reload files in views/layout folder

### ISSUE THREAD

**Issue by aqbjteddy** [MillerRen/vue-boilerplate#1]
Hi Miller,

I encountered a weird problem, page was not hot reloaded when I was editing files in views/layout folder, and I had to rerun "npm run dev" command to see new changes.

Do you have any good ideas?

Thanks,
Teddy

**Comment by MillerRen** [comment]
i renamed `layou`t to `Layout` fixed it, but i don't know why!

**Comment by aqbjteddy** [comment]
Thanks @MillerRen
